"""Dynamic scene presets for the Aqara Advanced Lighting integration.

This module contains all bundled dynamic scene presets, including original designs
and presets inspired by the Philips Hue scene gallery.
"""

from typing import Any, Final

from .const import (
    DISTRIBUTION_RANDOM,
    DISTRIBUTION_SHUFFLE_ROTATE,
    DISTRIBUTION_SYNCHRONIZED,
    END_BEHAVIOR_MAINTAIN,
    LOOP_MODE_CONTINUOUS,
)

# Dynamic scene bundled presets
DYNAMIC_SCENE_PRESETS: Final[dict[str, dict[str, Any]]] = {
    "sunset_glow": {
        "name": "Sunset Glow",
        "icon": "mdi:weather-sunset",
        "colors": [
            {"x": 0.5916, "y": 0.3824, "brightness_pct": 100},  # Deep orange
            {"x": 0.6399, "y": 0.3297, "brightness_pct": 87},  # Warm red
            {"x": 0.5143, "y": 0.4400, "brightness_pct": 90},  # Golden yellow
            {"x": 0.4112, "y": 0.2598, "brightness_pct": 92},  # Soft pink
        ],
        "transition_time": 120.0,
        "hold_time": 180.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 30.0,
        "random_order": False,
        "scene_brightness_pct": 70,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "ocean_waves": {
        "name": "Ocean Waves",
        "icon": "mdi:waves",
        "colors": [
            {"x": 0.1561, "y": 0.1547, "brightness_pct": 100},  # Deep blue
            {"x": 0.2038, "y": 0.3088, "brightness_pct": 87},  # Teal
            {"x": 0.2211, "y": 0.3494, "brightness_pct": 90},  # Cyan
            {"x": 0.2547, "y": 0.4053, "brightness_pct": 92},  # Seafoam green
        ],
        "transition_time": 90.0,
        "hold_time": 150.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 20.0,
        "random_order": False,
        "scene_brightness_pct": 60,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "northern_lights": {
        "name": "Northern Lights",
        "icon": "mdi:aurora",
        "colors": [
            {"x": 0.2151, "y": 0.5489, "brightness_pct": 100},  # Aurora green
            {"x": 0.2211, "y": 0.3494, "brightness_pct": 87},  # Cyan
            {"x": 0.2951, "y": 0.1783, "brightness_pct": 90},  # Purple
            {"x": 0.1561, "y": 0.0955, "brightness_pct": 92},  # Deep blue
            {"x": 0.3787, "y": 0.2238, "brightness_pct": 95},  # Magenta pink
        ],
        "transition_time": 180.0,
        "hold_time": 120.0,
        "distribution_mode": DISTRIBUTION_RANDOM,
        "offset_delay": 0.0,
        "random_order": False,
        "scene_brightness_pct": 50,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "relax": {
        "name": "Relax",
        "icon": "mdi:yoga",
        "colors": [
            {"x": 0.3127, "y": 0.2187, "brightness_pct": 100},  # Soft lavender
            {"x": 0.2436, "y": 0.2514, "brightness_pct": 85},  # Pale blue
        ],
        "transition_time": 300.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SYNCHRONIZED,
        "offset_delay": 0.0,
        "random_order": False,
        "scene_brightness_pct": 35,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "forest_canopy": {
        "name": "Forest Canopy",
        "icon": "mdi:pine-tree",
        "colors": [
            {"x": 0.2268, "y": 0.5012, "brightness_pct": 100},  # Deep forest green
            {"x": 0.2841, "y": 0.4763, "brightness_pct": 87},  # Moss green
            {"x": 0.3547, "y": 0.4489, "brightness_pct": 90},  # Olive
            {"x": 0.5016, "y": 0.4152, "brightness_pct": 92},  # Warm amber
        ],
        "transition_time": 240.0,
        "hold_time": 300.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 45.0,
        "random_order": False,
        "scene_brightness_pct": 45,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "fireplace": {
        "name": "Fireplace",
        "icon": "mdi:fire",
        "colors": [
            {"x": 0.6399, "y": 0.3297, "brightness_pct": 100},  # Deep red
            {"x": 0.5763, "y": 0.3842, "brightness_pct": 87},  # Burnt orange
            {"x": 0.5489, "y": 0.4075, "brightness_pct": 92},  # Dark amber
        ],
        "transition_time": 150.0,
        "hold_time": 210.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 30.0,
        "random_order": False,
        "scene_brightness_pct": 40,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "tropical_paradise": {
        "name": "Tropical Paradise",
        "icon": "mdi:island",
        "colors": [
            {"x": 0.2211, "y": 0.3494, "brightness_pct": 100},  # Turquoise
            {"x": 0.4112, "y": 0.3068, "brightness_pct": 87},  # Coral pink
            {"x": 0.4475, "y": 0.4521, "brightness_pct": 90},  # Sunny yellow
            {"x": 0.5916, "y": 0.3824, "brightness_pct": 92},  # Mango orange
        ],
        "transition_time": 120.0,
        "hold_time": 180.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 25.0,
        "random_order": False,
        "scene_brightness_pct": 65,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "deep_space": {
        "name": "Deep Space",
        "icon": "mdi:space-station",
        "colors": [
            {"x": 0.2743, "y": 0.1562, "brightness_pct": 100},  # Dark purple
            {"x": 0.1561, "y": 0.0812, "brightness_pct": 87},  # Deep blue
            {"x": 0.1472, "y": 0.0633, "brightness_pct": 90},  # Near-black blue
            {"x": 0.3214, "y": 0.1841, "brightness_pct": 92},  # Violet
        ],
        "transition_time": 300.0,
        "hold_time": 360.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 60.0,
        "random_order": False,
        "scene_brightness_pct": 30,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    # Hue-inspired scenes (from Philips Hue scene gallery)
    "cozy_embrace": {
        "name": "Cozy Embrace",
        "icon": "mdi:sofa",
        "colors": [
            {"x": 0.5734, "y": 0.327, "brightness_pct": 100},
            {"x": 0.5496, "y": 0.3804, "brightness_pct": 87},
            {"x": 0.5826, "y": 0.3426, "brightness_pct": 90},
            {"x": 0.5687, "y": 0.3667, "brightness_pct": 92},
            {"x": 0.5258, "y": 0.3976, "brightness_pct": 95},
        ],
        "transition_time": 180.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 20.0,
        "random_order": False,
        "scene_brightness_pct": 40,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "savanna_dusk": {
        "name": "Savanna Dusk",
        "icon": "mdi:weather-sunset-down",
        "colors": [
            {"x": 0.4162, "y": 0.4341, "brightness_pct": 100},
            {"x": 0.5862, "y": 0.3575, "brightness_pct": 87},
            {"x": 0.644, "y": 0.3348, "brightness_pct": 90},
            {"x": 0.5246, "y": 0.3864, "brightness_pct": 92},
            {"x": 0.4801, "y": 0.4309, "brightness_pct": 95},
        ],
        "transition_time": 240.0,
        "hold_time": 300.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 30.0,
        "random_order": False,
        "scene_brightness_pct": 58,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "golden_reflection": {
        "name": "Golden Reflection",
        "icon": "mdi:water-outline",
        "colors": [
            {"x": 0.5063, "y": 0.4474, "brightness_pct": 100},
            {"x": 0.5584, "y": 0.4083, "brightness_pct": 87},
            {"x": 0.5695, "y": 0.3999, "brightness_pct": 90},
            {"x": 0.482, "y": 0.4489, "brightness_pct": 92},
            {"x": 0.496, "y": 0.4424, "brightness_pct": 95},
        ],
        "transition_time": 300.0,
        "hold_time": 360.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 40.0,
        "random_order": False,
        "scene_brightness_pct": 64,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "miami_nights": {
        "name": "Miami Nights",
        "icon": "mdi:palm-tree",
        "colors": [
            {"x": 0.3678, "y": 0.1839, "brightness_pct": 100},
            {"x": 0.154, "y": 0.0799, "brightness_pct": 87},
            {"x": 0.5573, "y": 0.3226, "brightness_pct": 90},
            {"x": 0.1561, "y": 0.1606, "brightness_pct": 92},
            {"x": 0.4548, "y": 0.2433, "brightness_pct": 95},
        ],
        "transition_time": 60.0,
        "hold_time": 60.0,
        "distribution_mode": DISTRIBUTION_RANDOM,
        "offset_delay": 10.0,
        "random_order": False,
        "scene_brightness_pct": 79,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "rio_carnival": {
        "name": "Rio Carnival",
        "icon": "mdi:party-popper",
        "colors": [
            {"x": 0.4692, "y": 0.4536, "brightness_pct": 100},
            {"x": 0.5353, "y": 0.2909, "brightness_pct": 87},
            {"x": 0.5527, "y": 0.2686, "brightness_pct": 90},
            {"x": 0.2588, "y": 0.1266, "brightness_pct": 92},
            {"x": 0.5473, "y": 0.3735, "brightness_pct": 95},
        ],
        "transition_time": 120.0,
        "hold_time": 120.0,
        "distribution_mode": DISTRIBUTION_RANDOM,
        "offset_delay": 20.0,
        "random_order": False,
        "scene_brightness_pct": 79,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "ibiza_sunset": {
        "name": "Ibiza Sunset",
        "icon": "mdi:beach",
        "colors": [
            {"x": 0.5974, "y": 0.36, "brightness_pct": 100},
            {"x": 0.5286, "y": 0.4068, "brightness_pct": 87},
            {"x": 0.5714, "y": 0.3806, "brightness_pct": 90},
            {"x": 0.4376, "y": 0.4577, "brightness_pct": 92},
            {"x": 0.4787, "y": 0.4495, "brightness_pct": 95},
        ],
        "transition_time": 90.0,
        "hold_time": 90.0,
        "distribution_mode": DISTRIBUTION_RANDOM,
        "offset_delay": 15.0,
        "random_order": False,
        "scene_brightness_pct": 49,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "cosmic_galaxy": {
        "name": "Cosmic Galaxy",
        "icon": "mdi:galaxy-outline",
        "colors": [
            {"x": 0.4412, "y": 0.279, "brightness_pct": 100},
            {"x": 0.4845, "y": 0.2799, "brightness_pct": 87},
            {"x": 0.3502, "y": 0.1943, "brightness_pct": 90},
            {"x": 0.4844, "y": 0.2608, "brightness_pct": 92},
            {"x": 0.5351, "y": 0.3287, "brightness_pct": 95},
        ],
        "transition_time": 390.0,
        "hold_time": 480.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 45.0,
        "random_order": False,
        "scene_brightness_pct": 25,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "starlit_night": {
        "name": "Starlit Night",
        "icon": "mdi:star-outline",
        "colors": [
            {"x": 0.4387, "y": 0.3739, "brightness_pct": 100},
            {"x": 0.3133, "y": 0.2061, "brightness_pct": 87},
            {"x": 0.2213, "y": 0.1346, "brightness_pct": 90},
            {"x": 0.3787, "y": 0.2792, "brightness_pct": 92},
            {"x": 0.4228, "y": 0.3349, "brightness_pct": 95},
        ],
        "transition_time": 480.0,
        "hold_time": 600.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 60.0,
        "random_order": False,
        "scene_brightness_pct": 24,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "arctic_glow": {
        "name": "Arctic Glow",
        "icon": "mdi:aurora",
        "colors": [
            {"x": 0.1868, "y": 0.3328, "brightness_pct": 100},
            {"x": 0.1581, "y": 0.1508, "brightness_pct": 87},
            {"x": 0.1541, "y": 0.0844, "brightness_pct": 90},
            {"x": 0.2072, "y": 0.4525, "brightness_pct": 92},
            {"x": 0.2359, "y": 0.3855, "brightness_pct": 95},
        ],
        "transition_time": 300.0,
        "hold_time": 360.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 30.0,
        "random_order": False,
        "scene_brightness_pct": 26,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "tranquil_waters": {
        "name": "Tranquil Waters",
        "icon": "mdi:waves",
        "colors": [
            {"x": 0.4247, "y": 0.3033, "brightness_pct": 100},
            {"x": 0.3115, "y": 0.2261, "brightness_pct": 87},
            {"x": 0.2481, "y": 0.1608, "brightness_pct": 90},
            {"x": 0.3409, "y": 0.2472, "brightness_pct": 92},
            {"x": 0.3984, "y": 0.3182, "brightness_pct": 95},
        ],
        "transition_time": 180.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SYNCHRONIZED,
        "offset_delay": 0.0,
        "random_order": False,
        "scene_brightness_pct": 68,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "evening_sundown": {
        "name": "Evening Sundown",
        "icon": "mdi:weather-sunset",
        "colors": [
            {"x": 0.2459, "y": 0.2693, "brightness_pct": 100},
            {"x": 0.555, "y": 0.3606, "brightness_pct": 87},
            {"x": 0.192, "y": 0.1686, "brightness_pct": 90},
            {"x": 0.5948, "y": 0.3442, "brightness_pct": 92},
            {"x": 0.4848, "y": 0.3887, "brightness_pct": 95},
        ],
        "transition_time": 240.0,
        "hold_time": 270.0,
        "distribution_mode": DISTRIBUTION_SYNCHRONIZED,
        "offset_delay": 10.0,
        "random_order": False,
        "scene_brightness_pct": 50,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "azure_lagoon": {
        "name": "Azure Lagoon",
        "icon": "mdi:pool",
        "colors": [
            {"x": 0.1623, "y": 0.3254, "brightness_pct": 100},
            {"x": 0.464, "y": 0.3618, "brightness_pct": 87},
            {"x": 0.24, "y": 0.3475, "brightness_pct": 90},
            {"x": 0.304, "y": 0.3777, "brightness_pct": 92},
            {"x": 0.3962, "y": 0.4341, "brightness_pct": 95},
        ],
        "transition_time": 300.0,
        "hold_time": 300.0,
        "distribution_mode": DISTRIBUTION_SYNCHRONIZED,
        "offset_delay": 20.0,
        "random_order": False,
        "scene_brightness_pct": 50,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "alpine_breeze": {
        "name": "Alpine Breeze",
        "icon": "mdi:terrain",
        "colors": [
            {"x": 0.2361, "y": 0.2152, "brightness_pct": 100},
            {"x": 0.2557, "y": 0.2325, "brightness_pct": 87},
            {"x": 0.4271, "y": 0.4073, "brightness_pct": 90},
            {"x": 0.2238, "y": 0.2028, "brightness_pct": 92},
            {"x": 0.3836, "y": 0.3413, "brightness_pct": 95},
        ],
        "transition_time": 360.0,
        "hold_time": 420.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 45.0,
        "random_order": False,
        "scene_brightness_pct": 60,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "dawn_ocean": {
        "name": "Dawn Ocean",
        "icon": "mdi:weather-partly-rainy",
        "colors": [
            {"x": 0.4143, "y": 0.3548, "brightness_pct": 100},
            {"x": 0.3688, "y": 0.3106, "brightness_pct": 87},
            {"x": 0.2847, "y": 0.2449, "brightness_pct": 90},
            {"x": 0.4299, "y": 0.3951, "brightness_pct": 92},
            {"x": 0.4416, "y": 0.3743, "brightness_pct": 95},
        ],
        "transition_time": 240.0,
        "hold_time": 300.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 25.0,
        "random_order": False,
        "scene_brightness_pct": 84,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "blossom_spring": {
        "name": "Blossom Spring",
        "icon": "mdi:flower",
        "colors": [
            {"x": 0.3517, "y": 0.3154, "brightness_pct": 100},
            {"x": 0.3744, "y": 0.2692, "brightness_pct": 87},
            {"x": 0.359, "y": 0.2925, "brightness_pct": 90},
            {"x": 0.514, "y": 0.3338, "brightness_pct": 92},
            {"x": 0.4435, "y": 0.2537, "brightness_pct": 95},
        ],
        "transition_time": 300.0,
        "hold_time": 360.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 35.0,
        "random_order": False,
        "scene_brightness_pct": 60,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "morning_first_light": {
        "name": "Morning First Light",
        "icon": "mdi:weather-sunrise",
        "colors": [
            {"x": 0.1649, "y": 0.1783, "brightness_pct": 100},
            {"x": 0.5373, "y": 0.4003, "brightness_pct": 87},
            {"x": 0.3135, "y": 0.2404, "brightness_pct": 90},
            {"x": 0.2135, "y": 0.1847, "brightness_pct": 92},
            {"x": 0.4134, "y": 0.2962, "brightness_pct": 95},
        ],
        "transition_time": 120.0,
        "hold_time": 120.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 15.0,
        "random_order": False,
        "scene_brightness_pct": 30,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "distant_horizon": {
        "name": "Distant Horizon",
        "icon": "mdi:image-filter-hdr",
        "colors": [
            {"x": 0.1731, "y": 0.1978, "brightness_pct": 100},
            {"x": 0.5182, "y": 0.4136, "brightness_pct": 87},
            {"x": 0.2779, "y": 0.2188, "brightness_pct": 90},
            {"x": 0.1811, "y": 0.1979, "brightness_pct": 92},
            {"x": 0.5247, "y": 0.3877, "brightness_pct": 95},
        ],
        "transition_time": 180.0,
        "hold_time": 180.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 22.0,
        "random_order": False,
        "scene_brightness_pct": 50,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "solar_flare": {
        "name": "Solar Flare",
        "icon": "mdi:white-balance-sunny",
        "colors": [
            {"x": 0.2031, "y": 0.2342, "brightness_pct": 100},
            {"x": 0.481, "y": 0.4134, "brightness_pct": 87},
            {"x": 0.4448, "y": 0.3857, "brightness_pct": 90},
            {"x": 0.2556, "y": 0.2539, "brightness_pct": 92},
            {"x": 0.4967, "y": 0.414, "brightness_pct": 95},
        ],
        "transition_time": 240.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 30.0,
        "random_order": False,
        "scene_brightness_pct": 79,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "emerald_dream": {
        "name": "Emerald Dream",
        "icon": "mdi:butterfly",
        "colors": [
            {"x": 0.2099, "y": 0.344, "brightness_pct": 100},
            {"x": 0.1695, "y": 0.3125, "brightness_pct": 87},
            {"x": 0.319, "y": 0.3996, "brightness_pct": 90},
            {"x": 0.1593, "y": 0.25, "brightness_pct": 92},
            {"x": 0.1569, "y": 0.1897, "brightness_pct": 95},
        ],
        "transition_time": 240.0,
        "hold_time": 300.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 30.0,
        "random_order": False,
        "scene_brightness_pct": 40,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "scarlet_luxury": {
        "name": "Scarlet Luxury",
        "icon": "mdi:diamond-stone",
        "colors": [
            {"x": 0.4059, "y": 0.2562, "brightness_pct": 100},
            {"x": 0.5652, "y": 0.3006, "brightness_pct": 87},
            {"x": 0.5177, "y": 0.269, "brightness_pct": 90},
            {"x": 0.5829, "y": 0.3333, "brightness_pct": 92},
            {"x": 0.4585, "y": 0.2636, "brightness_pct": 95},
        ],
        "transition_time": 300.0,
        "hold_time": 360.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 45.0,
        "random_order": False,
        "scene_brightness_pct": 30,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "amber_blossom": {
        "name": "Amber Blossom",
        "icon": "mdi:flower-tulip",
        "colors": [
            {"x": 0.4934, "y": 0.3675, "brightness_pct": 100},
            {"x": 0.5717, "y": 0.3983, "brightness_pct": 87},
            {"x": 0.5341, "y": 0.3975, "brightness_pct": 90},
            {"x": 0.6178, "y": 0.3413, "brightness_pct": 92},
            {"x": 0.5946, "y": 0.3811, "brightness_pct": 95},
        ],
        "transition_time": 120.0,
        "hold_time": 180.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 20.0,
        "random_order": False,
        "scene_brightness_pct": 79,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "canvas_sky": {
        "name": "Canvas Sky",
        "icon": "mdi:palette",
        "colors": [
            {"x": 0.391, "y": 0.251, "brightness_pct": 100},
            {"x": 0.2214, "y": 0.1211, "brightness_pct": 87},
            {"x": 0.4707, "y": 0.3508, "brightness_pct": 90},
            {"x": 0.6206, "y": 0.3615, "brightness_pct": 92},
            {"x": 0.3106, "y": 0.1839, "brightness_pct": 95},
        ],
        "transition_time": 150.0,
        "hold_time": 210.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 27.0,
        "random_order": False,
        "scene_brightness_pct": 79,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "forest_journey": {
        "name": "Forest Journey",
        "icon": "mdi:pine-tree",
        "colors": [
            {"x": 0.1549, "y": 0.1144, "brightness_pct": 100},
            {"x": 0.1586, "y": 0.2169, "brightness_pct": 87},
            {"x": 0.4197, "y": 0.5125, "brightness_pct": 90},
            {"x": 0.2015, "y": 0.6023, "brightness_pct": 92},
            {"x": 0.3095, "y": 0.5913, "brightness_pct": 95},
        ],
        "transition_time": 180.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 35.0,
        "random_order": False,
        "scene_brightness_pct": 79,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "neon_wave": {
        "name": "Neon Wave",
        "icon": "mdi:waveform",
        "colors": [
            {"x": 0.1783, "y": 0.1212, "brightness_pct": 100},
            {"x": 0.2299, "y": 0.0862, "brightness_pct": 87},
            {"x": 0.474, "y": 0.4378, "brightness_pct": 90},
            {"x": 0.4039, "y": 0.1914, "brightness_pct": 92},
            {"x": 0.5403, "y": 0.4219, "brightness_pct": 95},
        ],
        "transition_time": 120.0,
        "hold_time": 180.0,
        "distribution_mode": DISTRIBUTION_RANDOM,
        "offset_delay": 15.0,
        "random_order": False,
        "scene_brightness_pct": 77,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "magnetic": {
        "name": "Magnetic",
        "icon": "mdi:magnet",
        "colors": [
            {"x": 0.4215, "y": 0.4895, "brightness_pct": 100},
            {"x": 0.1593, "y": 0.1341, "brightness_pct": 87},
            {"x": 0.516, "y": 0.4401, "brightness_pct": 90},
            {"x": 0.1575, "y": 0.2128, "brightness_pct": 92},
            {"x": 0.171, "y": 0.3389, "brightness_pct": 95},
        ],
        "transition_time": 240.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_RANDOM,
        "offset_delay": 30.0,
        "random_order": False,
        "scene_brightness_pct": 88,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "spring_awakening": {
        "name": "Spring Awakening",
        "icon": "mdi:flower-tulip-outline",
        "colors": [
            {"x": 0.5119, "y": 0.4249, "brightness_pct": 100},
            {"x": 0.3972, "y": 0.4025, "brightness_pct": 87},
            {"x": 0.4419, "y": 0.4164, "brightness_pct": 90},
            {"x": 0.2674, "y": 0.3018, "brightness_pct": 92},
            {"x": 0.24, "y": 0.2761, "brightness_pct": 95},
        ],
        "transition_time": 120.0,
        "hold_time": 180.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 20.0,
        "random_order": False,
        "scene_brightness_pct": 79,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "purple_bloom": {
        "name": "Purple Bloom",
        "icon": "mdi:flower",
        "colors": [
            {"x": 0.4195, "y": 0.4216, "brightness_pct": 100},
            {"x": 0.3818, "y": 0.485, "brightness_pct": 87},
            {"x": 0.2877, "y": 0.2519, "brightness_pct": 90},
            {"x": 0.2194, "y": 0.1332, "brightness_pct": 92},
            {"x": 0.4212, "y": 0.38, "brightness_pct": 95},
        ],
        "transition_time": 150.0,
        "hold_time": 210.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 25.0,
        "random_order": False,
        "scene_brightness_pct": 79,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "golden_narcissus": {
        "name": "Golden Narcissus",
        "icon": "mdi:flower-outline",
        "colors": [
            {"x": 0.5916, "y": 0.3833, "brightness_pct": 100},
            {"x": 0.485, "y": 0.4543, "brightness_pct": 87},
            {"x": 0.5475, "y": 0.4151, "brightness_pct": 90},
            {"x": 0.4451, "y": 0.4556, "brightness_pct": 92},
            {"x": 0.4759, "y": 0.4481, "brightness_pct": 95},
        ],
        "transition_time": 180.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 30.0,
        "random_order": False,
        "scene_brightness_pct": 90,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "cancun_party": {
        "name": "Cancun Party",
        "icon": "mdi:cocktail",
        "colors": [
            {"x": 0.5121, "y": 0.4371, "brightness_pct": 100},
            {"x": 0.6156, "y": 0.2808, "brightness_pct": 87},
            {"x": 0.6696, "y": 0.3237, "brightness_pct": 90},
            {"x": 0.5352, "y": 0.2797, "brightness_pct": 92},
            {"x": 0.6153, "y": 0.3655, "brightness_pct": 95},
        ],
        "transition_time": 60.0,
        "hold_time": 60.0,
        "distribution_mode": DISTRIBUTION_RANDOM,
        "offset_delay": 10.0,
        "random_order": False,
        "scene_brightness_pct": 79,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "osaka_night": {
        "name": "Osaka Night",
        "icon": "mdi:office-building",
        "colors": [
            {"x": 0.6222, "y": 0.3604, "brightness_pct": 100},
            {"x": 0.5532, "y": 0.2547, "brightness_pct": 87},
            {"x": 0.513, "y": 0.4237, "brightness_pct": 90},
            {"x": 0.5935, "y": 0.308, "brightness_pct": 92},
            {"x": 0.4519, "y": 0.2677, "brightness_pct": 95},
        ],
        "transition_time": 120.0,
        "hold_time": 120.0,
        "distribution_mode": DISTRIBUTION_RANDOM,
        "offset_delay": 20.0,
        "random_order": False,
        "scene_brightness_pct": 36,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "tokyo_neon": {
        "name": "Tokyo Neon",
        "icon": "mdi:city",
        "colors": [
            {"x": 0.5614, "y": 0.406, "brightness_pct": 100},
            {"x": 0.1753, "y": 0.0585, "brightness_pct": 87},
            {"x": 0.1562, "y": 0.1626, "brightness_pct": 90},
            {"x": 0.5894, "y": 0.2589, "brightness_pct": 92},
            {"x": 0.2676, "y": 0.103, "brightness_pct": 95},
        ],
        "transition_time": 90.0,
        "hold_time": 90.0,
        "distribution_mode": DISTRIBUTION_RANDOM,
        "offset_delay": 15.0,
        "random_order": False,
        "scene_brightness_pct": 47,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "dusk_dreams": {
        "name": "Dusk Dreams",
        "icon": "mdi:weather-night",
        "colors": [
            {"x": 0.5189, "y": 0.3924, "brightness_pct": 100},
            {"x": 0.5493, "y": 0.3702, "brightness_pct": 87},
            {"x": 0.4416, "y": 0.2813, "brightness_pct": 90},
            {"x": 0.4996, "y": 0.293, "brightness_pct": 92},
            {"x": 0.5579, "y": 0.3308, "brightness_pct": 95},
        ],
        "transition_time": 180.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 20.0,
        "random_order": False,
        "scene_brightness_pct": 50,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "ruby_radiance": {
        "name": "Ruby Radiance",
        "icon": "mdi:star-circle",
        "colors": [
            {"x": 0.3826, "y": 0.3117, "brightness_pct": 100},
            {"x": 0.5321, "y": 0.2758, "brightness_pct": 87},
            {"x": 0.4557, "y": 0.2951, "brightness_pct": 90},
            {"x": 0.4189, "y": 0.3031, "brightness_pct": 92},
            {"x": 0.4903, "y": 0.2839, "brightness_pct": 95},
        ],
        "transition_time": 300.0,
        "hold_time": 360.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 40.0,
        "random_order": False,
        "scene_brightness_pct": 40,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "twilight_tropics": {
        "name": "Twilight Tropics",
        "icon": "mdi:palm-tree",
        "colors": [
            {"x": 0.363, "y": 0.2716, "brightness_pct": 100},
            {"x": 0.4731, "y": 0.3723, "brightness_pct": 87},
            {"x": 0.5813, "y": 0.3636, "brightness_pct": 90},
            {"x": 0.2412, "y": 0.1171, "brightness_pct": 92},
            {"x": 0.3044, "y": 0.1803, "brightness_pct": 95},
        ],
        "transition_time": 240.0,
        "hold_time": 300.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 30.0,
        "random_order": False,
        "scene_brightness_pct": 44,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "crimson_moon": {
        "name": "Crimson Moon",
        "icon": "mdi:moon-full",
        "colors": [
            {"x": 0.3041, "y": 0.2368, "brightness_pct": 100},
            {"x": 0.1596, "y": 0.0684, "brightness_pct": 87},
            {"x": 0.3918, "y": 0.2958, "brightness_pct": 90},
            {"x": 0.1803, "y": 0.1298, "brightness_pct": 92},
            {"x": 0.465, "y": 0.3446, "brightness_pct": 95},
        ],
        "transition_time": 300.0,
        "hold_time": 360.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 30.0,
        "random_order": False,
        "scene_brightness_pct": 20,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "lunar_glow": {
        "name": "Lunar Glow",
        "icon": "mdi:moon-waning-crescent",
        "colors": [
            {"x": 0.2108, "y": 0.2047, "brightness_pct": 100},
            {"x": 0.1532, "y": 0.0476, "brightness_pct": 87},
            {"x": 0.3557, "y": 0.3352, "brightness_pct": 90},
            {"x": 0.1725, "y": 0.1532, "brightness_pct": 92},
            {"x": 0.1547, "y": 0.1074, "brightness_pct": 95},
        ],
        "transition_time": 390.0,
        "hold_time": 480.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 45.0,
        "random_order": False,
        "scene_brightness_pct": 20,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "stellar_nebula": {
        "name": "Stellar Nebula",
        "icon": "mdi:star-four-points",
        "colors": [
            {"x": 0.3161, "y": 0.2306, "brightness_pct": 100},
            {"x": 0.2712, "y": 0.1723, "brightness_pct": 87},
            {"x": 0.1911, "y": 0.0673, "brightness_pct": 90},
            {"x": 0.232, "y": 0.2056, "brightness_pct": 92},
            {"x": 0.3743, "y": 0.2727, "brightness_pct": 95},
        ],
        "transition_time": 480.0,
        "hold_time": 600.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 60.0,
        "random_order": False,
        "scene_brightness_pct": 24,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "amethyst_vale": {
        "name": "Amethyst Vale",
        "icon": "mdi:mountain",
        "colors": [
            {"x": 0.2977, "y": 0.2444, "brightness_pct": 100},
            {"x": 0.25, "y": 0.1781, "brightness_pct": 87},
            {"x": 0.2278, "y": 0.1424, "brightness_pct": 90},
            {"x": 0.2752, "y": 0.2042, "brightness_pct": 92},
            {"x": 0.2883, "y": 0.2235, "brightness_pct": 95},
        ],
        "transition_time": 180.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 25.0,
        "random_order": False,
        "scene_brightness_pct": 94,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "summer_solstice": {
        "name": "Summer Solstice",
        "icon": "mdi:white-balance-sunny",
        "colors": [
            {"x": 0.4134, "y": 0.4353, "brightness_pct": 100},
            {"x": 0.4351, "y": 0.4367, "brightness_pct": 87},
            {"x": 0.5247, "y": 0.4185, "brightness_pct": 90},
            {"x": 0.4532, "y": 0.4353, "brightness_pct": 92},
            {"x": 0.4849, "y": 0.4339, "brightness_pct": 95},
        ],
        "transition_time": 210.0,
        "hold_time": 270.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 30.0,
        "random_order": False,
        "scene_brightness_pct": 98,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "golden_autumn": {
        "name": "Golden Autumn",
        "icon": "mdi:leaf-maple",
        "colors": [
            {"x": 0.457, "y": 0.4406, "brightness_pct": 100},
            {"x": 0.4636, "y": 0.4073, "brightness_pct": 87},
            {"x": 0.4436, "y": 0.4271, "brightness_pct": 90},
            {"x": 0.4714, "y": 0.3964, "brightness_pct": 92},
            {"x": 0.4427, "y": 0.4017, "brightness_pct": 95},
        ],
        "transition_time": 240.0,
        "hold_time": 300.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 35.0,
        "random_order": False,
        "scene_brightness_pct": 79,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    # Phase 1 & 2: Gap-filling presets (from Philips Hue scene gallery)
    "spring_lake_reflection": {
        "name": "Spring Lake Reflection",
        "icon": "mdi:flower-tulip",
        "colors": [
            {"x": 0.3348, "y": 0.3611, "brightness_pct": 100},
            {"x": 0.3351, "y": 0.425, "brightness_pct": 87},
            {"x": 0.339, "y": 0.4042, "brightness_pct": 90},
            {"x": 0.3308, "y": 0.3798, "brightness_pct": 92},
            {"x": 0.3414, "y": 0.3868, "brightness_pct": 95},
        ],
        "transition_time": 180.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 25.0,
        "random_order": False,
        "scene_brightness_pct": 94,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "winter_peak": {
        "name": "Winter Peak",
        "icon": "mdi:snowflake",
        "colors": [
            {"x": 0.293, "y": 0.3236, "brightness_pct": 100},
            {"x": 0.2484, "y": 0.3089, "brightness_pct": 87},
            {"x": 0.252, "y": 0.3108, "brightness_pct": 90},
            {"x": 0.273, "y": 0.3175, "brightness_pct": 92},
            {"x": 0.2376, "y": 0.3042, "brightness_pct": 95},
        ],
        "transition_time": 300.0,
        "hold_time": 360.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 40.0,
        "random_order": False,
        "scene_brightness_pct": 88,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "blue_planet_dreams": {
        "name": "Blue Planet Dreams",
        "icon": "mdi:earth",
        "colors": [
            {"x": 0.1672, "y": 0.593, "brightness_pct": 100},
            {"x": 0.1915, "y": 0.3638, "brightness_pct": 87},
            {"x": 0.1624, "y": 0.4067, "brightness_pct": 90},
            {"x": 0.1566, "y": 0.1795, "brightness_pct": 92},
            {"x": 0.3314, "y": 0.5391, "brightness_pct": 95},
        ],
        "transition_time": 360.0,
        "hold_time": 420.0,
        "distribution_mode": DISTRIBUTION_SYNCHRONIZED,
        "offset_delay": 50.0,
        "random_order": False,
        "scene_brightness_pct": 54,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "misty_mountain": {
        "name": "Misty Mountain",
        "icon": "mdi:weather-fog",
        "colors": [
            {"x": 0.3441, "y": 0.3135, "brightness_pct": 100},
            {"x": 0.4125, "y": 0.3328, "brightness_pct": 87},
            {"x": 0.3793, "y": 0.3219, "brightness_pct": 90},
            {"x": 0.3648, "y": 0.3209, "brightness_pct": 92},
            {"x": 0.3955, "y": 0.3272, "brightness_pct": 95},
        ],
        "transition_time": 300.0,
        "hold_time": 360.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 40.0,
        "random_order": False,
        "scene_brightness_pct": 79,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "emerald_island": {
        "name": "Emerald Island",
        "icon": "mdi:island",
        "colors": [
            {"x": 0.4648, "y": 0.4254, "brightness_pct": 100},
            {"x": 0.3924, "y": 0.4132, "brightness_pct": 87},
            {"x": 0.2709, "y": 0.3235, "brightness_pct": 90},
            {"x": 0.255, "y": 0.4176, "brightness_pct": 92},
            {"x": 0.3134, "y": 0.4131, "brightness_pct": 95},
        ],
        "transition_time": 180.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 25.0,
        "random_order": False,
        "scene_brightness_pct": 75,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "winter_wonderland": {
        "name": "Winter Wonderland",
        "icon": "mdi:snowflake-variant",
        "colors": [
            {"x": 0.4216, "y": 0.4437, "brightness_pct": 100},
            {"x": 0.3281, "y": 0.4921, "brightness_pct": 87},
            {"x": 0.1784, "y": 0.3104, "brightness_pct": 90},
            {"x": 0.2137, "y": 0.49, "brightness_pct": 92},
            {"x": 0.5353, "y": 0.4074, "brightness_pct": 95},
        ],
        "transition_time": 300.0,
        "hold_time": 360.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 40.0,
        "random_order": False,
        "scene_brightness_pct": 79,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "precious_gems": {
        "name": "Precious Gems",
        "icon": "mdi:diamond",
        "colors": [
            {"x": 0.3951, "y": 0.3606, "brightness_pct": 100},
            {"x": 0.3493, "y": 0.209, "brightness_pct": 87},
            {"x": 0.3904, "y": 0.4336, "brightness_pct": 90},
            {"x": 0.3426, "y": 0.242, "brightness_pct": 92},
            {"x": 0.4384, "y": 0.3976, "brightness_pct": 95},
        ],
        "transition_time": 120.0,
        "hold_time": 180.0,
        "distribution_mode": DISTRIBUTION_RANDOM,
        "offset_delay": 20.0,
        "random_order": False,
        "scene_brightness_pct": 79,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "arctic_aurora_glow": {
        "name": "Arctic Aurora Glow",
        "icon": "mdi:snowflake-thermometer",
        "colors": [
            {"x": 0.1868, "y": 0.3328, "brightness_pct": 100},
            {"x": 0.1581, "y": 0.1508, "brightness_pct": 87},
            {"x": 0.1541, "y": 0.0844, "brightness_pct": 90},
            {"x": 0.2072, "y": 0.4525, "brightness_pct": 92},
            {"x": 0.2359, "y": 0.3855, "brightness_pct": 95},
        ],
        "transition_time": 180.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 25.0,
        "random_order": False,
        "scene_brightness_pct": 26,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "blue_lagoon_paradise": {
        "name": "Blue Lagoon Paradise",
        "icon": "mdi:waves",
        "colors": [
            {"x": 0.1623, "y": 0.3254, "brightness_pct": 100},
            {"x": 0.464, "y": 0.3618, "brightness_pct": 87},
            {"x": 0.24, "y": 0.3475, "brightness_pct": 90},
            {"x": 0.304, "y": 0.3777, "brightness_pct": 92},
            {"x": 0.3962, "y": 0.4341, "brightness_pct": 95},
        ],
        "transition_time": 180.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 25.0,
        "random_order": False,
        "scene_brightness_pct": 50,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "tyrell_vision": {
        "name": "Tyrell Vision",
        "icon": "mdi:eye",
        "colors": [
            {"x": 0.2267, "y": 0.0832, "brightness_pct": 100},
            {"x": 0.37, "y": 0.2328, "brightness_pct": 87},
            {"x": 0.3977, "y": 0.1832, "brightness_pct": 90},
            {"x": 0.1586, "y": 0.2579, "brightness_pct": 92},
            {"x": 0.257, "y": 0.1754, "brightness_pct": 95},
        ],
        "transition_time": 180.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 25.0,
        "random_order": False,
        "scene_brightness_pct": 50,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "disturbia_lights": {
        "name": "Disturbia Lights",
        "icon": "mdi:lightbulb-multiple",
        "colors": [
            {"x": 0.3864, "y": 0.1864, "brightness_pct": 100},
            {"x": 0.5305, "y": 0.261, "brightness_pct": 87},
            {"x": 0.6587, "y": 0.2924, "brightness_pct": 90},
            {"x": 0.2132, "y": 0.3113, "brightness_pct": 92},
            {"x": 0.1616, "y": 0.3754, "brightness_pct": 95},
        ],
        "transition_time": 180.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 25.0,
        "random_order": False,
        "scene_brightness_pct": 62,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
    "palm_beach_sunset": {
        "name": "Palm Beach Sunset",
        "icon": "mdi:palm-tree",
        "colors": [
            {"x": 0.5691, "y": 0.3512, "brightness_pct": 100},
            {"x": 0.4824, "y": 0.3325, "brightness_pct": 87},
            {"x": 0.3888, "y": 0.2997, "brightness_pct": 90},
            {"x": 0.2576, "y": 0.3185, "brightness_pct": 92},
            {"x": 0.2007, "y": 0.3418, "brightness_pct": 95},
        ],
        "transition_time": 180.0,
        "hold_time": 240.0,
        "distribution_mode": DISTRIBUTION_SHUFFLE_ROTATE,
        "offset_delay": 25.0,
        "random_order": False,
        "scene_brightness_pct": 38,
        "loop_mode": LOOP_MODE_CONTINUOUS,
        "end_behavior": END_BEHAVIOR_MAINTAIN,
    },
}
